// Copyright (c) 2025 Egor Lazarchuk
// SPDX-License-Identifier: MIT
//
// This file is auto generated by gen/physical_device_features_gen.zig

const std = @import("std");
const log = @import("log.zig");
const vk = @import("volk.zig");

vk_physical_device_16bit_storage_features: vk.VkPhysicalDevice16BitStorageFeatures =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_16BIT_STORAGE_FEATURES },
vk_physical_device_multiview_features: vk.VkPhysicalDeviceMultiviewFeatures =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_FEATURES },
vk_physical_device_variable_pointers_features: vk.VkPhysicalDeviceVariablePointersFeatures =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VARIABLE_POINTERS_FEATURES },
vk_physical_device_sampler_ycbcr_conversion_features: vk.VkPhysicalDeviceSamplerYcbcrConversionFeatures =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SAMPLER_YCBCR_CONVERSION_FEATURES },
vk_physical_device_shader_draw_parameters_features: vk.VkPhysicalDeviceShaderDrawParametersFeatures =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_DRAW_PARAMETERS_FEATURES },
vk_physical_device_8bit_storage_features: vk.VkPhysicalDevice8BitStorageFeatures =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_8BIT_STORAGE_FEATURES },
vk_physical_device_shader_atomic_int64_features: vk.VkPhysicalDeviceShaderAtomicInt64Features =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_ATOMIC_INT64_FEATURES },
vk_physical_device_shader_float16_int8_features: vk.VkPhysicalDeviceShaderFloat16Int8Features =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_FLOAT16_INT8_FEATURES },
vk_physical_device_descriptor_indexing_features: vk.VkPhysicalDeviceDescriptorIndexingFeatures =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_INDEXING_FEATURES },
vk_physical_device_vulkan_memory_model_features: vk.VkPhysicalDeviceVulkanMemoryModelFeatures =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_MEMORY_MODEL_FEATURES },
vk_physical_device_uniform_buffer_standard_layout_features: vk.VkPhysicalDeviceUniformBufferStandardLayoutFeatures =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_UNIFORM_BUFFER_STANDARD_LAYOUT_FEATURES },
vk_physical_device_shader_subgroup_extended_types_features: vk.VkPhysicalDeviceShaderSubgroupExtendedTypesFeatures =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_SUBGROUP_EXTENDED_TYPES_FEATURES },
vk_physical_device_separate_depth_stencil_layouts_features: vk.VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SEPARATE_DEPTH_STENCIL_LAYOUTS_FEATURES },
vk_physical_device_buffer_device_address_features: vk.VkPhysicalDeviceBufferDeviceAddressFeatures =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_BUFFER_DEVICE_ADDRESS_FEATURES },
vk_physical_device_shader_clock_features_khr: vk.VkPhysicalDeviceShaderClockFeaturesKHR =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_CLOCK_FEATURES_KHR },
vk_physical_device_fragment_shading_rate_features_khr: vk.VkPhysicalDeviceFragmentShadingRateFeaturesKHR =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FRAGMENT_SHADING_RATE_FEATURES_KHR },
vk_physical_device_ray_query_features_khr: vk.VkPhysicalDeviceRayQueryFeaturesKHR =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAY_QUERY_FEATURES_KHR },
vk_physical_device_ray_tracing_pipeline_features_khr: vk.VkPhysicalDeviceRayTracingPipelineFeaturesKHR =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAY_TRACING_PIPELINE_FEATURES_KHR },
vk_physical_device_acceleration_structure_features_khr: vk.VkPhysicalDeviceAccelerationStructureFeaturesKHR =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ACCELERATION_STRUCTURE_FEATURES_KHR },
vk_physical_device_workgroup_memory_explicit_layout_features_khr: vk.VkPhysicalDeviceWorkgroupMemoryExplicitLayoutFeaturesKHR =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_WORKGROUP_MEMORY_EXPLICIT_LAYOUT_FEATURES_KHR },
vk_physical_device_shader_integer_dot_product_features_khr: vk.VkPhysicalDeviceShaderIntegerDotProductFeaturesKHR =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_INTEGER_DOT_PRODUCT_FEATURES_KHR },
vk_physical_device_synchronization_2_features_khr: vk.VkPhysicalDeviceSynchronization2FeaturesKHR =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SYNCHRONIZATION_2_FEATURES_KHR },
vk_physical_device_dynamic_rendering_features_khr: vk.VkPhysicalDeviceDynamicRenderingFeaturesKHR =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DYNAMIC_RENDERING_FEATURES_KHR },
vk_physical_device_maintenance_4_features_khr: vk.VkPhysicalDeviceMaintenance4FeaturesKHR =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_4_FEATURES_KHR },
vk_physical_device_maintenance_5_features_khr: vk.VkPhysicalDeviceMaintenance5FeaturesKHR =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_5_FEATURES_KHR },
vk_physical_device_maintenance_7_features_khr: vk.VkPhysicalDeviceMaintenance7FeaturesKHR =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_7_FEATURES_KHR },
vk_physical_device_zero_initialize_workgroup_memory_features_khr: vk.VkPhysicalDeviceZeroInitializeWorkgroupMemoryFeaturesKHR =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ZERO_INITIALIZE_WORKGROUP_MEMORY_FEATURES_KHR },
vk_physical_device_transform_feedback_features_ext: vk.VkPhysicalDeviceTransformFeedbackFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TRANSFORM_FEEDBACK_FEATURES_EXT },
vk_physical_device_depth_clip_enable_features_ext: vk.VkPhysicalDeviceDepthClipEnableFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DEPTH_CLIP_ENABLE_FEATURES_EXT },
vk_physical_device_inline_uniform_block_features_ext: vk.VkPhysicalDeviceInlineUniformBlockFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_INLINE_UNIFORM_BLOCK_FEATURES_EXT },
vk_physical_device_blend_operation_advanced_features_ext: vk.VkPhysicalDeviceBlendOperationAdvancedFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_BLEND_OPERATION_ADVANCED_FEATURES_EXT },
vk_physical_device_vertex_attribute_divisor_features_khr: vk.VkPhysicalDeviceVertexAttributeDivisorFeaturesKHR =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VERTEX_ATTRIBUTE_DIVISOR_FEATURES_KHR },
vk_physical_device_shader_demote_to_helper_invocation_features_ext: vk.VkPhysicalDeviceShaderDemoteToHelperInvocationFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_DEMOTE_TO_HELPER_INVOCATION_FEATURES_EXT },
vk_physical_device_fragment_shader_interlock_features_ext: vk.VkPhysicalDeviceFragmentShaderInterlockFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FRAGMENT_SHADER_INTERLOCK_FEATURES_EXT },
vk_physical_device_fragment_density_map_features_ext: vk.VkPhysicalDeviceFragmentDensityMapFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FRAGMENT_DENSITY_MAP_FEATURES_EXT },
vk_physical_device_buffer_device_address_features_ext: vk.VkPhysicalDeviceBufferDeviceAddressFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_BUFFER_DEVICE_ADDRESS_FEATURES_EXT },
vk_physical_device_line_rasterization_features_khr: vk.VkPhysicalDeviceLineRasterizationFeaturesKHR =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_LINE_RASTERIZATION_FEATURES_KHR },
vk_physical_device_subgroup_size_control_features_ext: vk.VkPhysicalDeviceSubgroupSizeControlFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBGROUP_SIZE_CONTROL_FEATURES_EXT },
vk_physical_device_extended_dynamic_state_features_ext: vk.VkPhysicalDeviceExtendedDynamicStateFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTENDED_DYNAMIC_STATE_FEATURES_EXT },
vk_physical_device_extended_dynamic_state_2_features_ext: vk.VkPhysicalDeviceExtendedDynamicState2FeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTENDED_DYNAMIC_STATE_2_FEATURES_EXT },
vk_physical_device_extended_dynamic_state_3_features_ext: vk.VkPhysicalDeviceExtendedDynamicState3FeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTENDED_DYNAMIC_STATE_3_FEATURES_EXT },
vk_physical_device_vertex_input_dynamic_state_features_ext: vk.VkPhysicalDeviceVertexInputDynamicStateFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VERTEX_INPUT_DYNAMIC_STATE_FEATURES_EXT },
vk_physical_device_color_write_enable_features_ext: vk.VkPhysicalDeviceColorWriteEnableFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COLOR_WRITE_ENABLE_FEATURES_EXT },
vk_physical_device_shader_image_atomic_int64_features_ext: vk.VkPhysicalDeviceShaderImageAtomicInt64FeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_IMAGE_ATOMIC_INT64_FEATURES_EXT },
vk_physical_device_shader_atomic_float_features_ext: vk.VkPhysicalDeviceShaderAtomicFloatFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_ATOMIC_FLOAT_FEATURES_EXT },
vk_physical_device_shader_atomic_float_2_features_ext: vk.VkPhysicalDeviceShaderAtomicFloat2FeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_ATOMIC_FLOAT_2_FEATURES_EXT },
vk_physical_device_provoking_vertex_features_ext: vk.VkPhysicalDeviceProvokingVertexFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROVOKING_VERTEX_FEATURES_EXT },
vk_physical_device_custom_border_color_features_ext: vk.VkPhysicalDeviceCustomBorderColorFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CUSTOM_BORDER_COLOR_FEATURES_EXT },
vk_physical_device_compute_shader_derivatives_features_khr: vk.VkPhysicalDeviceComputeShaderDerivativesFeaturesKHR =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COMPUTE_SHADER_DERIVATIVES_FEATURES_KHR },
vk_physical_device_fragment_shader_barycentric_features_khr: vk.VkPhysicalDeviceFragmentShaderBarycentricFeaturesKHR =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FRAGMENT_SHADER_BARYCENTRIC_FEATURES_KHR },
vk_physical_device_shader_image_footprint_features_nv: vk.VkPhysicalDeviceShaderImageFootprintFeaturesNV =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_IMAGE_FOOTPRINT_FEATURES_NV },
vk_physical_device_shading_rate_image_features_nv: vk.VkPhysicalDeviceShadingRateImageFeaturesNV =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADING_RATE_IMAGE_FEATURES_NV },
vk_physical_device_cooperative_matrix_features_nv: vk.VkPhysicalDeviceCooperativeMatrixFeaturesNV =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COOPERATIVE_MATRIX_FEATURES_NV },
vk_physical_device_shader_sm_builtins_features_nv: vk.VkPhysicalDeviceShaderSMBuiltinsFeaturesNV =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_SM_BUILTINS_FEATURES_NV },
vk_physical_device_shader_integer_functions_2_features_intel: vk.VkPhysicalDeviceShaderIntegerFunctions2FeaturesINTEL =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_INTEGER_FUNCTIONS_2_FEATURES_INTEL },
vk_physical_device_mutable_descriptor_type_features_ext: vk.VkPhysicalDeviceMutableDescriptorTypeFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MUTABLE_DESCRIPTOR_TYPE_FEATURES_EXT },
vk_physical_device_robustness_2_features_ext: vk.VkPhysicalDeviceRobustness2FeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ROBUSTNESS_2_FEATURES_EXT },
vk_physical_device_image_robustness_features_ext: vk.VkPhysicalDeviceImageRobustnessFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_ROBUSTNESS_FEATURES_EXT },
vk_physical_device_graphics_pipeline_library_features_ext: vk.VkPhysicalDeviceGraphicsPipelineLibraryFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_GRAPHICS_PIPELINE_LIBRARY_FEATURES_EXT },
vk_physical_device_fragment_shading_rate_enums_features_nv: vk.VkPhysicalDeviceFragmentShadingRateEnumsFeaturesNV =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FRAGMENT_SHADING_RATE_ENUMS_FEATURES_NV },
vk_physical_device_depth_clip_control_features_ext: vk.VkPhysicalDeviceDepthClipControlFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DEPTH_CLIP_CONTROL_FEATURES_EXT },
vk_physical_device_mesh_shader_features_nv: vk.VkPhysicalDeviceMeshShaderFeaturesNV =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MESH_SHADER_FEATURES_NV },
vk_physical_device_mesh_shader_features_ext: vk.VkPhysicalDeviceMeshShaderFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MESH_SHADER_FEATURES_EXT },
vk_physical_device_descriptor_buffer_features_ext: vk.VkPhysicalDeviceDescriptorBufferFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_BUFFER_FEATURES_EXT },
vk_physical_device_non_seamless_cube_map_features_ext: vk.VkPhysicalDeviceNonSeamlessCubeMapFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_NON_SEAMLESS_CUBE_MAP_FEATURES_EXT },
vk_physical_device_attachment_feedback_loop_layout_features_ext: vk.VkPhysicalDeviceAttachmentFeedbackLoopLayoutFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ATTACHMENT_FEEDBACK_LOOP_LAYOUT_FEATURES_EXT },
vk_physical_device_shader_module_identifier_features_ext: vk.VkPhysicalDeviceShaderModuleIdentifierFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_MODULE_IDENTIFIER_FEATURES_EXT },
vk_physical_device_ray_tracing_maintenance_1_features_khr: vk.VkPhysicalDeviceRayTracingMaintenance1FeaturesKHR =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAY_TRACING_MAINTENANCE_1_FEATURES_KHR },
vk_physical_device_ray_tracing_motion_blur_features_nv: vk.VkPhysicalDeviceRayTracingMotionBlurFeaturesNV =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAY_TRACING_MOTION_BLUR_FEATURES_NV },
vk_physical_device_image_processing_features_qcom: vk.VkPhysicalDeviceImageProcessingFeaturesQCOM =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_PROCESSING_FEATURES_QCOM },
vk_physical_device_image_processing_2_features_qcom: vk.VkPhysicalDeviceImageProcessing2FeaturesQCOM =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_PROCESSING_2_FEATURES_QCOM },
vk_physical_device_shader_core_builtins_features_arm: vk.VkPhysicalDeviceShaderCoreBuiltinsFeaturesARM =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_CORE_BUILTINS_FEATURES_ARM },
vk_physical_device_ray_tracing_position_fetch_features_khr: vk.VkPhysicalDeviceRayTracingPositionFetchFeaturesKHR =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAY_TRACING_POSITION_FETCH_FEATURES_KHR },
vk_physical_device_shader_tile_image_features_ext: vk.VkPhysicalDeviceShaderTileImageFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_TILE_IMAGE_FEATURES_EXT },
vk_physical_device_cooperative_matrix_features_khr: vk.VkPhysicalDeviceCooperativeMatrixFeaturesKHR =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COOPERATIVE_MATRIX_FEATURES_KHR },
vk_physical_device_shader_subgroup_rotate_features_khr: vk.VkPhysicalDeviceShaderSubgroupRotateFeaturesKHR =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_SUBGROUP_ROTATE_FEATURES_KHR },
vk_physical_device_shader_expect_assume_features_khr: vk.VkPhysicalDeviceShaderExpectAssumeFeaturesKHR =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_EXPECT_ASSUME_FEATURES_KHR },
vk_physical_device_shader_float_controls_2_features_khr: vk.VkPhysicalDeviceShaderFloatControls2FeaturesKHR =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_FLOAT_CONTROLS_2_FEATURES_KHR },
vk_physical_device_shader_quad_control_features_khr: vk.VkPhysicalDeviceShaderQuadControlFeaturesKHR =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_QUAD_CONTROL_FEATURES_KHR },
vk_physical_device_raw_access_chains_features_nv: vk.VkPhysicalDeviceRawAccessChainsFeaturesNV =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAW_ACCESS_CHAINS_FEATURES_NV },
vk_physical_device_shader_replicated_composites_features_ext: vk.VkPhysicalDeviceShaderReplicatedCompositesFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_REPLICATED_COMPOSITES_FEATURES_EXT },
vk_physical_device_pipeline_robustness_features_ext: vk.VkPhysicalDevicePipelineRobustnessFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PIPELINE_ROBUSTNESS_FEATURES_EXT },
vk_physical_device_conditional_rendering_features_ext: vk.VkPhysicalDeviceConditionalRenderingFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CONDITIONAL_RENDERING_FEATURES_EXT },
vk_physical_device_dynamic_rendering_local_read_features_khr: vk.VkPhysicalDeviceDynamicRenderingLocalReadFeaturesKHR =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DYNAMIC_RENDERING_LOCAL_READ_FEATURES_KHR },
vk_physical_device_rasterization_order_attachment_access_features_ext: vk.VkPhysicalDeviceRasterizationOrderAttachmentAccessFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RASTERIZATION_ORDER_ATTACHMENT_ACCESS_FEATURES_EXT },
vk_physical_device_opacity_micromap_features_ext: vk.VkPhysicalDeviceOpacityMicromapFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_OPACITY_MICROMAP_FEATURES_EXT },
vk_physical_device_device_generated_commands_features_nv: vk.VkPhysicalDeviceDeviceGeneratedCommandsFeaturesNV =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DEVICE_GENERATED_COMMANDS_FEATURES_NV },
vk_physical_device_device_generated_commands_compute_features_nv: vk.VkPhysicalDeviceDeviceGeneratedCommandsComputeFeaturesNV =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DEVICE_GENERATED_COMMANDS_COMPUTE_FEATURES_NV },
vk_physical_device_optical_flow_features_nv: vk.VkPhysicalDeviceOpticalFlowFeaturesNV =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_OPTICAL_FLOW_FEATURES_NV },
vk_physical_device_legacy_dithering_features_ext: vk.VkPhysicalDeviceLegacyDitheringFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_LEGACY_DITHERING_FEATURES_EXT },
vk_physical_device_pipeline_protected_access_features_ext: vk.VkPhysicalDevicePipelineProtectedAccessFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PIPELINE_PROTECTED_ACCESS_FEATURES_EXT },
vk_physical_device_per_stage_descriptor_set_features_nv: vk.VkPhysicalDevicePerStageDescriptorSetFeaturesNV =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PER_STAGE_DESCRIPTOR_SET_FEATURES_NV },
vk_physical_device_attachment_feedback_loop_dynamic_state_features_ext: vk.VkPhysicalDeviceAttachmentFeedbackLoopDynamicStateFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ATTACHMENT_FEEDBACK_LOOP_DYNAMIC_STATE_FEATURES_EXT },
vk_physical_device_subpass_merge_feedback_features_ext: vk.VkPhysicalDeviceSubpassMergeFeedbackFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBPASS_MERGE_FEEDBACK_FEATURES_EXT },
vk_physical_device_border_color_swizzle_features_ext: vk.VkPhysicalDeviceBorderColorSwizzleFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_BORDER_COLOR_SWIZZLE_FEATURES_EXT },
vk_physical_device_multisampled_render_to_single_sampled_features_ext: vk.VkPhysicalDeviceMultisampledRenderToSingleSampledFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTISAMPLED_RENDER_TO_SINGLE_SAMPLED_FEATURES_EXT },
vk_physical_device_depth_bias_control_features_ext: vk.VkPhysicalDeviceDepthBiasControlFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DEPTH_BIAS_CONTROL_FEATURES_EXT },
vk_physical_device_depth_clamp_control_features_ext: vk.VkPhysicalDeviceDepthClampControlFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DEPTH_CLAMP_CONTROL_FEATURES_EXT },
vk_physical_device_device_generated_commands_features_ext: vk.VkPhysicalDeviceDeviceGeneratedCommandsFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DEVICE_GENERATED_COMMANDS_FEATURES_EXT },
vk_physical_device_shader_object_features_ext: vk.VkPhysicalDeviceShaderObjectFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_OBJECT_FEATURES_EXT },
vk_physical_device_primitives_generated_query_features_ext: vk.VkPhysicalDevicePrimitivesGeneratedQueryFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PRIMITIVES_GENERATED_QUERY_FEATURES_EXT },
vk_physical_device_image_2d_view_of_3d_features_ext: vk.VkPhysicalDeviceImage2DViewOf3DFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_2D_VIEW_OF_3D_FEATURES_EXT },
vk_physical_device_scalar_block_layout_features_ext: vk.VkPhysicalDeviceScalarBlockLayoutFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SCALAR_BLOCK_LAYOUT_FEATURES_EXT },
vk_physical_device_shader_bfloat16_features_khr: vk.VkPhysicalDeviceShaderBfloat16FeaturesKHR =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_BFLOAT16_FEATURES_KHR },
vk_physical_device_cooperative_matrix_2_features_nv: vk.VkPhysicalDeviceCooperativeMatrix2FeaturesNV =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COOPERATIVE_MATRIX_2_FEATURES_NV },
vk_physical_device_ray_tracing_linear_swept_spheres_features_nv: vk.VkPhysicalDeviceRayTracingLinearSweptSpheresFeaturesNV =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAY_TRACING_LINEAR_SWEPT_SPHERES_FEATURES_NV },
vk_physical_device_cluster_acceleration_structure_features_nv: vk.VkPhysicalDeviceClusterAccelerationStructureFeaturesNV =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CLUSTER_ACCELERATION_STRUCTURE_FEATURES_NV },
vk_physical_device_cooperative_vector_features_nv: vk.VkPhysicalDeviceCooperativeVectorFeaturesNV =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COOPERATIVE_VECTOR_FEATURES_NV },
vk_physical_device_tile_shading_features_qcom: vk.VkPhysicalDeviceTileShadingFeaturesQCOM =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TILE_SHADING_FEATURES_QCOM },
vk_physical_device_shader_float8_features_ext: vk.VkPhysicalDeviceShaderFloat8FeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_FLOAT8_FEATURES_EXT },
vk_physical_device_tensor_features_arm: vk.VkPhysicalDeviceTensorFeaturesARM =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TENSOR_FEATURES_ARM },
vk_physical_device_zero_initialize_device_memory_features_ext: vk.VkPhysicalDeviceZeroInitializeDeviceMemoryFeaturesEXT =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ZERO_INITIALIZE_DEVICE_MEMORY_FEATURES_EXT },
vk_physical_device_pipeline_opacity_micromap_features_arm: vk.VkPhysicalDevicePipelineOpacityMicromapFeaturesARM =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PIPELINE_OPACITY_MICROMAP_FEATURES_ARM },
vk_physical_device_partitioned_acceleration_structure_features_nv: vk.VkPhysicalDevicePartitionedAccelerationStructureFeaturesNV =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PARTITIONED_ACCELERATION_STRUCTURE_FEATURES_NV },
vk_physical_device_fragment_density_map_layered_features_valve: vk.VkPhysicalDeviceFragmentDensityMapLayeredFeaturesVALVE =
    .{ .sType = vk.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FRAGMENT_DENSITY_MAP_LAYERED_FEATURES_VALVE },

pub fn chain_supported(features: *@This(), extensions: [][*c]const u8) ?*anyopaque {
    var pnext: ?*anyopaque = null;
    for (extensions) |ext| {
        const e = std.mem.span(ext);
        if (std.mem.eql(u8, e, vk.VK_VALVE_FRAGMENT_DENSITY_MAP_LAYERED_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_VALVE_FRAGMENT_DENSITY_MAP_LAYERED_EXTENSION_NAME});
            features.vk_physical_device_fragment_density_map_layered_features_valve.pNext = pnext;
            pnext = &features.vk_physical_device_fragment_density_map_layered_features_valve;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_NV_PARTITIONED_ACCELERATION_STRUCTURE_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_NV_PARTITIONED_ACCELERATION_STRUCTURE_EXTENSION_NAME});
            features.vk_physical_device_partitioned_acceleration_structure_features_nv.pNext = pnext;
            pnext = &features.vk_physical_device_partitioned_acceleration_structure_features_nv;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_ARM_PIPELINE_OPACITY_MICROMAP_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_ARM_PIPELINE_OPACITY_MICROMAP_EXTENSION_NAME});
            features.vk_physical_device_pipeline_opacity_micromap_features_arm.pNext = pnext;
            pnext = &features.vk_physical_device_pipeline_opacity_micromap_features_arm;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_ZERO_INITIALIZE_DEVICE_MEMORY_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_ZERO_INITIALIZE_DEVICE_MEMORY_EXTENSION_NAME});
            features.vk_physical_device_zero_initialize_device_memory_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_zero_initialize_device_memory_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_ARM_TENSORS_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_ARM_TENSORS_EXTENSION_NAME});
            features.vk_physical_device_tensor_features_arm.pNext = pnext;
            pnext = &features.vk_physical_device_tensor_features_arm;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_SHADER_FLOAT8_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_SHADER_FLOAT8_EXTENSION_NAME});
            features.vk_physical_device_shader_float8_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_shader_float8_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_QCOM_TILE_SHADING_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_QCOM_TILE_SHADING_EXTENSION_NAME});
            features.vk_physical_device_tile_shading_features_qcom.pNext = pnext;
            pnext = &features.vk_physical_device_tile_shading_features_qcom;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_NV_COOPERATIVE_VECTOR_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_NV_COOPERATIVE_VECTOR_EXTENSION_NAME});
            features.vk_physical_device_cooperative_vector_features_nv.pNext = pnext;
            pnext = &features.vk_physical_device_cooperative_vector_features_nv;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_NV_CLUSTER_ACCELERATION_STRUCTURE_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_NV_CLUSTER_ACCELERATION_STRUCTURE_EXTENSION_NAME});
            features.vk_physical_device_cluster_acceleration_structure_features_nv.pNext = pnext;
            pnext = &features.vk_physical_device_cluster_acceleration_structure_features_nv;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_NV_RAY_TRACING_LINEAR_SWEPT_SPHERES_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_NV_RAY_TRACING_LINEAR_SWEPT_SPHERES_EXTENSION_NAME});
            features.vk_physical_device_ray_tracing_linear_swept_spheres_features_nv.pNext = pnext;
            pnext = &features.vk_physical_device_ray_tracing_linear_swept_spheres_features_nv;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_NV_COOPERATIVE_MATRIX_2_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_NV_COOPERATIVE_MATRIX_2_EXTENSION_NAME});
            features.vk_physical_device_cooperative_matrix_2_features_nv.pNext = pnext;
            pnext = &features.vk_physical_device_cooperative_matrix_2_features_nv;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_SHADER_BFLOAT16_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_SHADER_BFLOAT16_EXTENSION_NAME});
            features.vk_physical_device_shader_bfloat16_features_khr.pNext = pnext;
            pnext = &features.vk_physical_device_shader_bfloat16_features_khr;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_SCALAR_BLOCK_LAYOUT_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_SCALAR_BLOCK_LAYOUT_EXTENSION_NAME});
            features.vk_physical_device_scalar_block_layout_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_scalar_block_layout_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_IMAGE_2D_VIEW_OF_3D_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_IMAGE_2D_VIEW_OF_3D_EXTENSION_NAME});
            features.vk_physical_device_image_2d_view_of_3d_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_image_2d_view_of_3d_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_PRIMITIVES_GENERATED_QUERY_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_PRIMITIVES_GENERATED_QUERY_EXTENSION_NAME});
            features.vk_physical_device_primitives_generated_query_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_primitives_generated_query_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_SHADER_OBJECT_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_SHADER_OBJECT_EXTENSION_NAME});
            features.vk_physical_device_shader_object_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_shader_object_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_DEVICE_GENERATED_COMMANDS_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_DEVICE_GENERATED_COMMANDS_EXTENSION_NAME});
            features.vk_physical_device_device_generated_commands_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_device_generated_commands_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_DEPTH_CLAMP_CONTROL_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_DEPTH_CLAMP_CONTROL_EXTENSION_NAME});
            features.vk_physical_device_depth_clamp_control_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_depth_clamp_control_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_DEPTH_BIAS_CONTROL_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_DEPTH_BIAS_CONTROL_EXTENSION_NAME});
            features.vk_physical_device_depth_bias_control_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_depth_bias_control_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_MULTISAMPLED_RENDER_TO_SINGLE_SAMPLED_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_MULTISAMPLED_RENDER_TO_SINGLE_SAMPLED_EXTENSION_NAME});
            features.vk_physical_device_multisampled_render_to_single_sampled_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_multisampled_render_to_single_sampled_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_BORDER_COLOR_SWIZZLE_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_BORDER_COLOR_SWIZZLE_EXTENSION_NAME});
            features.vk_physical_device_border_color_swizzle_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_border_color_swizzle_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_SUBPASS_MERGE_FEEDBACK_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_SUBPASS_MERGE_FEEDBACK_EXTENSION_NAME});
            features.vk_physical_device_subpass_merge_feedback_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_subpass_merge_feedback_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_ATTACHMENT_FEEDBACK_LOOP_DYNAMIC_STATE_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_ATTACHMENT_FEEDBACK_LOOP_DYNAMIC_STATE_EXTENSION_NAME});
            features.vk_physical_device_attachment_feedback_loop_dynamic_state_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_attachment_feedback_loop_dynamic_state_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_NV_PER_STAGE_DESCRIPTOR_SET_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_NV_PER_STAGE_DESCRIPTOR_SET_EXTENSION_NAME});
            features.vk_physical_device_per_stage_descriptor_set_features_nv.pNext = pnext;
            pnext = &features.vk_physical_device_per_stage_descriptor_set_features_nv;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_PIPELINE_PROTECTED_ACCESS_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_PIPELINE_PROTECTED_ACCESS_EXTENSION_NAME});
            features.vk_physical_device_pipeline_protected_access_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_pipeline_protected_access_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_LEGACY_DITHERING_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_LEGACY_DITHERING_EXTENSION_NAME});
            features.vk_physical_device_legacy_dithering_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_legacy_dithering_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_NV_OPTICAL_FLOW_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_NV_OPTICAL_FLOW_EXTENSION_NAME});
            features.vk_physical_device_optical_flow_features_nv.pNext = pnext;
            pnext = &features.vk_physical_device_optical_flow_features_nv;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_NV_DEVICE_GENERATED_COMMANDS_COMPUTE_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_NV_DEVICE_GENERATED_COMMANDS_COMPUTE_EXTENSION_NAME});
            features.vk_physical_device_device_generated_commands_compute_features_nv.pNext = pnext;
            pnext = &features.vk_physical_device_device_generated_commands_compute_features_nv;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_NV_DEVICE_GENERATED_COMMANDS_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_NV_DEVICE_GENERATED_COMMANDS_EXTENSION_NAME});
            features.vk_physical_device_device_generated_commands_features_nv.pNext = pnext;
            pnext = &features.vk_physical_device_device_generated_commands_features_nv;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_OPACITY_MICROMAP_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_OPACITY_MICROMAP_EXTENSION_NAME});
            features.vk_physical_device_opacity_micromap_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_opacity_micromap_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_RASTERIZATION_ORDER_ATTACHMENT_ACCESS_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_RASTERIZATION_ORDER_ATTACHMENT_ACCESS_EXTENSION_NAME});
            features.vk_physical_device_rasterization_order_attachment_access_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_rasterization_order_attachment_access_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_DYNAMIC_RENDERING_LOCAL_READ_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_DYNAMIC_RENDERING_LOCAL_READ_EXTENSION_NAME});
            features.vk_physical_device_dynamic_rendering_local_read_features_khr.pNext = pnext;
            pnext = &features.vk_physical_device_dynamic_rendering_local_read_features_khr;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_CONDITIONAL_RENDERING_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_CONDITIONAL_RENDERING_EXTENSION_NAME});
            features.vk_physical_device_conditional_rendering_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_conditional_rendering_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_PIPELINE_ROBUSTNESS_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_PIPELINE_ROBUSTNESS_EXTENSION_NAME});
            features.vk_physical_device_pipeline_robustness_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_pipeline_robustness_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_SHADER_REPLICATED_COMPOSITES_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_SHADER_REPLICATED_COMPOSITES_EXTENSION_NAME});
            features.vk_physical_device_shader_replicated_composites_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_shader_replicated_composites_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_NV_RAW_ACCESS_CHAINS_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_NV_RAW_ACCESS_CHAINS_EXTENSION_NAME});
            features.vk_physical_device_raw_access_chains_features_nv.pNext = pnext;
            pnext = &features.vk_physical_device_raw_access_chains_features_nv;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_SHADER_QUAD_CONTROL_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_SHADER_QUAD_CONTROL_EXTENSION_NAME});
            features.vk_physical_device_shader_quad_control_features_khr.pNext = pnext;
            pnext = &features.vk_physical_device_shader_quad_control_features_khr;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_SHADER_FLOAT_CONTROLS_2_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_SHADER_FLOAT_CONTROLS_2_EXTENSION_NAME});
            features.vk_physical_device_shader_float_controls_2_features_khr.pNext = pnext;
            pnext = &features.vk_physical_device_shader_float_controls_2_features_khr;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_SHADER_EXPECT_ASSUME_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_SHADER_EXPECT_ASSUME_EXTENSION_NAME});
            features.vk_physical_device_shader_expect_assume_features_khr.pNext = pnext;
            pnext = &features.vk_physical_device_shader_expect_assume_features_khr;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_SHADER_SUBGROUP_ROTATE_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_SHADER_SUBGROUP_ROTATE_EXTENSION_NAME});
            features.vk_physical_device_shader_subgroup_rotate_features_khr.pNext = pnext;
            pnext = &features.vk_physical_device_shader_subgroup_rotate_features_khr;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_COOPERATIVE_MATRIX_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_COOPERATIVE_MATRIX_EXTENSION_NAME});
            features.vk_physical_device_cooperative_matrix_features_khr.pNext = pnext;
            pnext = &features.vk_physical_device_cooperative_matrix_features_khr;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_SHADER_TILE_IMAGE_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_SHADER_TILE_IMAGE_EXTENSION_NAME});
            features.vk_physical_device_shader_tile_image_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_shader_tile_image_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_RAY_TRACING_POSITION_FETCH_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_RAY_TRACING_POSITION_FETCH_EXTENSION_NAME});
            features.vk_physical_device_ray_tracing_position_fetch_features_khr.pNext = pnext;
            pnext = &features.vk_physical_device_ray_tracing_position_fetch_features_khr;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_ARM_SHADER_CORE_BUILTINS_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_ARM_SHADER_CORE_BUILTINS_EXTENSION_NAME});
            features.vk_physical_device_shader_core_builtins_features_arm.pNext = pnext;
            pnext = &features.vk_physical_device_shader_core_builtins_features_arm;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_QCOM_IMAGE_PROCESSING_2_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_QCOM_IMAGE_PROCESSING_2_EXTENSION_NAME});
            features.vk_physical_device_image_processing_2_features_qcom.pNext = pnext;
            pnext = &features.vk_physical_device_image_processing_2_features_qcom;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_QCOM_IMAGE_PROCESSING_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_QCOM_IMAGE_PROCESSING_EXTENSION_NAME});
            features.vk_physical_device_image_processing_features_qcom.pNext = pnext;
            pnext = &features.vk_physical_device_image_processing_features_qcom;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_NV_RAY_TRACING_MOTION_BLUR_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_NV_RAY_TRACING_MOTION_BLUR_EXTENSION_NAME});
            features.vk_physical_device_ray_tracing_motion_blur_features_nv.pNext = pnext;
            pnext = &features.vk_physical_device_ray_tracing_motion_blur_features_nv;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_RAY_TRACING_MAINTENANCE_1_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_RAY_TRACING_MAINTENANCE_1_EXTENSION_NAME});
            features.vk_physical_device_ray_tracing_maintenance_1_features_khr.pNext = pnext;
            pnext = &features.vk_physical_device_ray_tracing_maintenance_1_features_khr;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_SHADER_MODULE_IDENTIFIER_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_SHADER_MODULE_IDENTIFIER_EXTENSION_NAME});
            features.vk_physical_device_shader_module_identifier_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_shader_module_identifier_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_ATTACHMENT_FEEDBACK_LOOP_LAYOUT_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_ATTACHMENT_FEEDBACK_LOOP_LAYOUT_EXTENSION_NAME});
            features.vk_physical_device_attachment_feedback_loop_layout_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_attachment_feedback_loop_layout_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_NON_SEAMLESS_CUBE_MAP_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_NON_SEAMLESS_CUBE_MAP_EXTENSION_NAME});
            features.vk_physical_device_non_seamless_cube_map_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_non_seamless_cube_map_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_DESCRIPTOR_BUFFER_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_DESCRIPTOR_BUFFER_EXTENSION_NAME});
            features.vk_physical_device_descriptor_buffer_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_descriptor_buffer_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_MESH_SHADER_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_MESH_SHADER_EXTENSION_NAME});
            features.vk_physical_device_mesh_shader_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_mesh_shader_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_NV_MESH_SHADER_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_NV_MESH_SHADER_EXTENSION_NAME});
            features.vk_physical_device_mesh_shader_features_nv.pNext = pnext;
            pnext = &features.vk_physical_device_mesh_shader_features_nv;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_DEPTH_CLIP_CONTROL_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_DEPTH_CLIP_CONTROL_EXTENSION_NAME});
            features.vk_physical_device_depth_clip_control_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_depth_clip_control_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_NV_FRAGMENT_SHADING_RATE_ENUMS_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_NV_FRAGMENT_SHADING_RATE_ENUMS_EXTENSION_NAME});
            features.vk_physical_device_fragment_shading_rate_enums_features_nv.pNext = pnext;
            pnext = &features.vk_physical_device_fragment_shading_rate_enums_features_nv;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_GRAPHICS_PIPELINE_LIBRARY_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_GRAPHICS_PIPELINE_LIBRARY_EXTENSION_NAME});
            features.vk_physical_device_graphics_pipeline_library_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_graphics_pipeline_library_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_IMAGE_ROBUSTNESS_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_IMAGE_ROBUSTNESS_EXTENSION_NAME});
            features.vk_physical_device_image_robustness_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_image_robustness_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_ROBUSTNESS_2_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_ROBUSTNESS_2_EXTENSION_NAME});
            features.vk_physical_device_robustness_2_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_robustness_2_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_MUTABLE_DESCRIPTOR_TYPE_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_MUTABLE_DESCRIPTOR_TYPE_EXTENSION_NAME});
            features.vk_physical_device_mutable_descriptor_type_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_mutable_descriptor_type_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_INTEL_SHADER_INTEGER_FUNCTIONS_2_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_INTEL_SHADER_INTEGER_FUNCTIONS_2_EXTENSION_NAME});
            features.vk_physical_device_shader_integer_functions_2_features_intel.pNext = pnext;
            pnext = &features.vk_physical_device_shader_integer_functions_2_features_intel;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_NV_SHADER_SM_BUILTINS_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_NV_SHADER_SM_BUILTINS_EXTENSION_NAME});
            features.vk_physical_device_shader_sm_builtins_features_nv.pNext = pnext;
            pnext = &features.vk_physical_device_shader_sm_builtins_features_nv;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_NV_COOPERATIVE_MATRIX_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_NV_COOPERATIVE_MATRIX_EXTENSION_NAME});
            features.vk_physical_device_cooperative_matrix_features_nv.pNext = pnext;
            pnext = &features.vk_physical_device_cooperative_matrix_features_nv;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_NV_SHADING_RATE_IMAGE_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_NV_SHADING_RATE_IMAGE_EXTENSION_NAME});
            features.vk_physical_device_shading_rate_image_features_nv.pNext = pnext;
            pnext = &features.vk_physical_device_shading_rate_image_features_nv;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_NV_SHADER_IMAGE_FOOTPRINT_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_NV_SHADER_IMAGE_FOOTPRINT_EXTENSION_NAME});
            features.vk_physical_device_shader_image_footprint_features_nv.pNext = pnext;
            pnext = &features.vk_physical_device_shader_image_footprint_features_nv;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_FRAGMENT_SHADER_BARYCENTRIC_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_FRAGMENT_SHADER_BARYCENTRIC_EXTENSION_NAME});
            features.vk_physical_device_fragment_shader_barycentric_features_khr.pNext = pnext;
            pnext = &features.vk_physical_device_fragment_shader_barycentric_features_khr;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_COMPUTE_SHADER_DERIVATIVES_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_COMPUTE_SHADER_DERIVATIVES_EXTENSION_NAME});
            features.vk_physical_device_compute_shader_derivatives_features_khr.pNext = pnext;
            pnext = &features.vk_physical_device_compute_shader_derivatives_features_khr;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_CUSTOM_BORDER_COLOR_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_CUSTOM_BORDER_COLOR_EXTENSION_NAME});
            features.vk_physical_device_custom_border_color_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_custom_border_color_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_PROVOKING_VERTEX_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_PROVOKING_VERTEX_EXTENSION_NAME});
            features.vk_physical_device_provoking_vertex_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_provoking_vertex_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_SHADER_ATOMIC_FLOAT_2_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_SHADER_ATOMIC_FLOAT_2_EXTENSION_NAME});
            features.vk_physical_device_shader_atomic_float_2_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_shader_atomic_float_2_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_SHADER_ATOMIC_FLOAT_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_SHADER_ATOMIC_FLOAT_EXTENSION_NAME});
            features.vk_physical_device_shader_atomic_float_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_shader_atomic_float_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_SHADER_IMAGE_ATOMIC_INT64_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_SHADER_IMAGE_ATOMIC_INT64_EXTENSION_NAME});
            features.vk_physical_device_shader_image_atomic_int64_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_shader_image_atomic_int64_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_COLOR_WRITE_ENABLE_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_COLOR_WRITE_ENABLE_EXTENSION_NAME});
            features.vk_physical_device_color_write_enable_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_color_write_enable_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_VERTEX_INPUT_DYNAMIC_STATE_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_VERTEX_INPUT_DYNAMIC_STATE_EXTENSION_NAME});
            features.vk_physical_device_vertex_input_dynamic_state_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_vertex_input_dynamic_state_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_EXTENDED_DYNAMIC_STATE_3_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_EXTENDED_DYNAMIC_STATE_3_EXTENSION_NAME});
            features.vk_physical_device_extended_dynamic_state_3_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_extended_dynamic_state_3_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_EXTENDED_DYNAMIC_STATE_2_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_EXTENDED_DYNAMIC_STATE_2_EXTENSION_NAME});
            features.vk_physical_device_extended_dynamic_state_2_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_extended_dynamic_state_2_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_EXTENDED_DYNAMIC_STATE_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_EXTENDED_DYNAMIC_STATE_EXTENSION_NAME});
            features.vk_physical_device_extended_dynamic_state_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_extended_dynamic_state_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_SUBGROUP_SIZE_CONTROL_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_SUBGROUP_SIZE_CONTROL_EXTENSION_NAME});
            features.vk_physical_device_subgroup_size_control_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_subgroup_size_control_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_LINE_RASTERIZATION_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_LINE_RASTERIZATION_EXTENSION_NAME});
            features.vk_physical_device_line_rasterization_features_khr.pNext = pnext;
            pnext = &features.vk_physical_device_line_rasterization_features_khr;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_BUFFER_DEVICE_ADDRESS_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_BUFFER_DEVICE_ADDRESS_EXTENSION_NAME});
            features.vk_physical_device_buffer_device_address_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_buffer_device_address_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_FRAGMENT_DENSITY_MAP_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_FRAGMENT_DENSITY_MAP_EXTENSION_NAME});
            features.vk_physical_device_fragment_density_map_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_fragment_density_map_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_FRAGMENT_SHADER_INTERLOCK_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_FRAGMENT_SHADER_INTERLOCK_EXTENSION_NAME});
            features.vk_physical_device_fragment_shader_interlock_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_fragment_shader_interlock_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_SHADER_DEMOTE_TO_HELPER_INVOCATION_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_SHADER_DEMOTE_TO_HELPER_INVOCATION_EXTENSION_NAME});
            features.vk_physical_device_shader_demote_to_helper_invocation_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_shader_demote_to_helper_invocation_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_VERTEX_ATTRIBUTE_DIVISOR_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_VERTEX_ATTRIBUTE_DIVISOR_EXTENSION_NAME});
            features.vk_physical_device_vertex_attribute_divisor_features_khr.pNext = pnext;
            pnext = &features.vk_physical_device_vertex_attribute_divisor_features_khr;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_BLEND_OPERATION_ADVANCED_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_BLEND_OPERATION_ADVANCED_EXTENSION_NAME});
            features.vk_physical_device_blend_operation_advanced_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_blend_operation_advanced_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_INLINE_UNIFORM_BLOCK_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_INLINE_UNIFORM_BLOCK_EXTENSION_NAME});
            features.vk_physical_device_inline_uniform_block_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_inline_uniform_block_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_DEPTH_CLIP_ENABLE_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_DEPTH_CLIP_ENABLE_EXTENSION_NAME});
            features.vk_physical_device_depth_clip_enable_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_depth_clip_enable_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_TRANSFORM_FEEDBACK_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_TRANSFORM_FEEDBACK_EXTENSION_NAME});
            features.vk_physical_device_transform_feedback_features_ext.pNext = pnext;
            pnext = &features.vk_physical_device_transform_feedback_features_ext;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_ZERO_INITIALIZE_WORKGROUP_MEMORY_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_ZERO_INITIALIZE_WORKGROUP_MEMORY_EXTENSION_NAME});
            features.vk_physical_device_zero_initialize_workgroup_memory_features_khr.pNext = pnext;
            pnext = &features.vk_physical_device_zero_initialize_workgroup_memory_features_khr;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_MAINTENANCE_7_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_MAINTENANCE_7_EXTENSION_NAME});
            features.vk_physical_device_maintenance_7_features_khr.pNext = pnext;
            pnext = &features.vk_physical_device_maintenance_7_features_khr;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_MAINTENANCE_5_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_MAINTENANCE_5_EXTENSION_NAME});
            features.vk_physical_device_maintenance_5_features_khr.pNext = pnext;
            pnext = &features.vk_physical_device_maintenance_5_features_khr;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_MAINTENANCE_4_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_MAINTENANCE_4_EXTENSION_NAME});
            features.vk_physical_device_maintenance_4_features_khr.pNext = pnext;
            pnext = &features.vk_physical_device_maintenance_4_features_khr;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_DYNAMIC_RENDERING_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_DYNAMIC_RENDERING_EXTENSION_NAME});
            features.vk_physical_device_dynamic_rendering_features_khr.pNext = pnext;
            pnext = &features.vk_physical_device_dynamic_rendering_features_khr;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_SYNCHRONIZATION_2_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_SYNCHRONIZATION_2_EXTENSION_NAME});
            features.vk_physical_device_synchronization_2_features_khr.pNext = pnext;
            pnext = &features.vk_physical_device_synchronization_2_features_khr;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_SHADER_INTEGER_DOT_PRODUCT_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_SHADER_INTEGER_DOT_PRODUCT_EXTENSION_NAME});
            features.vk_physical_device_shader_integer_dot_product_features_khr.pNext = pnext;
            pnext = &features.vk_physical_device_shader_integer_dot_product_features_khr;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_WORKGROUP_MEMORY_EXPLICIT_LAYOUT_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_WORKGROUP_MEMORY_EXPLICIT_LAYOUT_EXTENSION_NAME});
            features.vk_physical_device_workgroup_memory_explicit_layout_features_khr.pNext = pnext;
            pnext = &features.vk_physical_device_workgroup_memory_explicit_layout_features_khr;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_ACCELERATION_STRUCTURE_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_ACCELERATION_STRUCTURE_EXTENSION_NAME});
            features.vk_physical_device_acceleration_structure_features_khr.pNext = pnext;
            pnext = &features.vk_physical_device_acceleration_structure_features_khr;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_RAY_TRACING_PIPELINE_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_RAY_TRACING_PIPELINE_EXTENSION_NAME});
            features.vk_physical_device_ray_tracing_pipeline_features_khr.pNext = pnext;
            pnext = &features.vk_physical_device_ray_tracing_pipeline_features_khr;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_RAY_QUERY_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_RAY_QUERY_EXTENSION_NAME});
            features.vk_physical_device_ray_query_features_khr.pNext = pnext;
            pnext = &features.vk_physical_device_ray_query_features_khr;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_FRAGMENT_SHADING_RATE_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_FRAGMENT_SHADING_RATE_EXTENSION_NAME});
            features.vk_physical_device_fragment_shading_rate_features_khr.pNext = pnext;
            pnext = &features.vk_physical_device_fragment_shading_rate_features_khr;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_SHADER_CLOCK_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_SHADER_CLOCK_EXTENSION_NAME});
            features.vk_physical_device_shader_clock_features_khr.pNext = pnext;
            pnext = &features.vk_physical_device_shader_clock_features_khr;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_BUFFER_DEVICE_ADDRESS_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_BUFFER_DEVICE_ADDRESS_EXTENSION_NAME});
            features.vk_physical_device_buffer_device_address_features.pNext = pnext;
            pnext = &features.vk_physical_device_buffer_device_address_features;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_SEPARATE_DEPTH_STENCIL_LAYOUTS_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_SEPARATE_DEPTH_STENCIL_LAYOUTS_EXTENSION_NAME});
            features.vk_physical_device_separate_depth_stencil_layouts_features.pNext = pnext;
            pnext = &features.vk_physical_device_separate_depth_stencil_layouts_features;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_SHADER_SUBGROUP_EXTENDED_TYPES_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_SHADER_SUBGROUP_EXTENDED_TYPES_EXTENSION_NAME});
            features.vk_physical_device_shader_subgroup_extended_types_features.pNext = pnext;
            pnext = &features.vk_physical_device_shader_subgroup_extended_types_features;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_UNIFORM_BUFFER_STANDARD_LAYOUT_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_UNIFORM_BUFFER_STANDARD_LAYOUT_EXTENSION_NAME});
            features.vk_physical_device_uniform_buffer_standard_layout_features.pNext = pnext;
            pnext = &features.vk_physical_device_uniform_buffer_standard_layout_features;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_VULKAN_MEMORY_MODEL_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_VULKAN_MEMORY_MODEL_EXTENSION_NAME});
            features.vk_physical_device_vulkan_memory_model_features.pNext = pnext;
            pnext = &features.vk_physical_device_vulkan_memory_model_features;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_EXT_DESCRIPTOR_INDEXING_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_EXT_DESCRIPTOR_INDEXING_EXTENSION_NAME});
            features.vk_physical_device_descriptor_indexing_features.pNext = pnext;
            pnext = &features.vk_physical_device_descriptor_indexing_features;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_SHADER_FLOAT16_INT8_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_SHADER_FLOAT16_INT8_EXTENSION_NAME});
            features.vk_physical_device_shader_float16_int8_features.pNext = pnext;
            pnext = &features.vk_physical_device_shader_float16_int8_features;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_SHADER_ATOMIC_INT64_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_SHADER_ATOMIC_INT64_EXTENSION_NAME});
            features.vk_physical_device_shader_atomic_int64_features.pNext = pnext;
            pnext = &features.vk_physical_device_shader_atomic_int64_features;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_8BIT_STORAGE_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_8BIT_STORAGE_EXTENSION_NAME});
            features.vk_physical_device_8bit_storage_features.pNext = pnext;
            pnext = &features.vk_physical_device_8bit_storage_features;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_SHADER_DRAW_PARAMETERS_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_SHADER_DRAW_PARAMETERS_EXTENSION_NAME});
            features.vk_physical_device_shader_draw_parameters_features.pNext = pnext;
            pnext = &features.vk_physical_device_shader_draw_parameters_features;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_SAMPLER_YCBCR_CONVERSION_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_SAMPLER_YCBCR_CONVERSION_EXTENSION_NAME});
            features.vk_physical_device_sampler_ycbcr_conversion_features.pNext = pnext;
            pnext = &features.vk_physical_device_sampler_ycbcr_conversion_features;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_VARIABLE_POINTERS_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_VARIABLE_POINTERS_EXTENSION_NAME});
            features.vk_physical_device_variable_pointers_features.pNext = pnext;
            pnext = &features.vk_physical_device_variable_pointers_features;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_MULTIVIEW_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_MULTIVIEW_EXTENSION_NAME});
            features.vk_physical_device_multiview_features.pNext = pnext;
            pnext = &features.vk_physical_device_multiview_features;
            continue;
        }
        if (std.mem.eql(u8, e, vk.VK_KHR_16BIT_STORAGE_EXTENSION_NAME)) {
            log.debug(@src(), "Adding {s} extension to the physical device features pnext chain", .{vk.VK_KHR_16BIT_STORAGE_EXTENSION_NAME});
            features.vk_physical_device_16bit_storage_features.pNext = pnext;
            pnext = &features.vk_physical_device_16bit_storage_features;
            continue;
        }
    }
    return pnext;
}
